apiVersion: v1
kind: ConfigMap
metadata:
  name: repforge-config
  namespace: repforge
data:
  ASPNETCORE_ENVIRONMENT: Production
  Entra__Authority: https://repforgecustomers.ciamlogin.com/144ce918-4124-41e9-9cce-8d2204fd1cde/v2.0
  Entra__ClientId: 3cb03558-710b-4a35-a82c-8936f112ac25
  Cors__AllowedOrigins__0: https://20.56.202.212
